### ISSUE TITLE
Is it possible to enable collection of queue related metrics?

### ISSUE THREAD

**Issue by rafal-szypulka** [ibm-messaging/mq-container#232]
After enabling Prometheus metrics, I can see only Queue Manager (ibmmq_qmgr*) metrics. Is there any way to enable queue related metrics like ibmmq_object* in mq container? 

[Here]( https://github.com/ibm-messaging/mq-metric-samples/tree/master/cmd/mq_prometheus#configuring-mq) it is described how to configure it for 'traditional' MQ. Question is how to achieve the same for MQ container running on ICP?

**Comment by parrobe** [comment]
Hi @rafal-szypulka , it is not currently possible to enable queue based metrics. In order to enable queue based metrics there needs to be a mechanism to pass the queues you would like metrics for down to the metric client in order for it to subscribe to them. This does not exist yet.

I have an item on our internal backlog to enable this in the future, i will add that you are interested in this functionality.
