### ISSUE TITLE
differences between master branch and 9.0.5

### ISSUE THREAD

**Issue by cra1gl1** [ibm-messaging/mq-container#239]
You say master branch is not stable. Could you please tell how much behind 9.0.5 is compared  to the master?

**Comment by parrobe** [comment]
Hi @cra1gl1 - we roughly detail what changes go into each release of this repository in the [CHANGELOG](https://github.com/ibm-messaging/mq-container/blob/master/CHANGELOG.md) file. 

The master branch has had additional changes made since 9.1.0.0 was released in July. There will likely be a change coming in the next few days that will show what these are.
