### ISSUE TITLE
../vendor/github.com/ibm-messaging/mq-golang/ibmmq/mqi.go:57:18: fatal error: cmqc.h: No such file or directory

### ISSUE THREAD

**Issue by VSA13** [ibm-messaging/mq-container#271]
I am encountering the following issue when building RHEL image for MQ 9.1.1. I have updated the packages to MQ_PACKAGES ?= MQSeriesRuntime-*.rpm MQSeriesClient*.rpm MQSeriesSDK*.rpm MQSeriesServer-*.rpm MQSeriesJava*.rpm MQSeriesJRE*.rpm MQSeriesGSKit*.rpm MQSeriesMsg*.rpm in BuildRHEL file, but still the issue persists.

**Comment by VSA13** [comment]
![image](https://user-images.githubusercontent.com/43268079/52209170-fb5fee00-287a-11e9-9b60-f4e4700676d7.png)

**Comment by arthurbarr** [comment]
The MQ redistributable client is what contains `cmqc.h`.  It looks like the TAR file for the client is getting extracted — it may be worth checking the SDK image under `/opt/mqm`, to make sure that it's working OK.  FWIW, my copy of `9.1.1.0-IBM-MQC-Redist-LinuxX64.tar.gz` is 66540186 bytes.

**Comment by VSA13** [comment]
Hi Arthur,

My copy of is mqadv_dev911_linux_x86-64.tar.gz is 842,420,616 bytes. 
I am trying to get MQ server RHEL image built using the instructions. But the build fails due to **fatal error: cmqc.h: No such file or directory**. 
I have checked the MQSeriesSDK*.rpm in RHEL build file. Is the issue due to licensing ?

**Comment by arthurbarr** [comment]
No, the problem is not related to licensing.

Note that you are working off the latest "master" branch, which is not always stable.  We have made some recent changes in this area.  If you just want to get something working, I'd suggest you switch to 9.1.1 branch.

The Go programs which we add to the container use the MQ *client* to connect to the local MQ server.  We need to compile those programs, so need a copy of the MQ C client header files.  In the current release (i.e. the 9.1.1 branch), those header files are obtained by installing the MQSeriesSDK RPM.  In the master branch, we have switched to using the MQ "redistributable" client instead, which also includes the header files.  This has not yet been fully documented, as it's in development at the moment.  From your screenshot, it looks like you've got a copy of the redistributable client file (`9.1.1.0-IBM-MQC-Redist-LinuxX64.tar.gz`), but something is going wrong with it, and the file isn't where expected.

**Comment by VSA13** [comment]
I tried with the 9.1.1 branch, but I am getting a different error as below.
**sudo groupadd --root /var/lib/containers/storage/overlay/b55fec423f4ff9a59d2b0                                                                                                         3009b0da150736709ec4e812499205063bb1089adac/merged --system --gid 888 mqm
groupadd: failure while writing changes to /etc/group
make: *** [build-mqgolang-sdk-ex] Error 10**

**Comment by arthurbarr** [comment]
OK.  I believe that error is related to having SELinux enabled on your host.  There are fixes for that in the master branch, so I guess you're going to have to press ahead with that.

I'm afraid I can't reproduce your problem at all.  Can I ask you for some more details, as per my previous comments?  The problem is that one or more files are not getting extracted properly, so we need to establish either what files you have in your `9.1.1.0-IBM-MQC-Redist-LinuxX64.tar.gz`) and/or what files appear in the `/opt/mqm` directory in the SDK image.

**Comment by arthurbarr** [comment]
OK.  Renaming the file was the problem, as they are different files.  You need two files in your downloads directory:

* [mqadv_dev911_linux_x86-64.tar.gz](https://public.dhe.ibm.com/ibmdl/export/pub/software/websphere/messaging/mqadv/mqadv_dev911_linux_x86-64.tar.gz)
* [9.1.1.0-IBM-MQC-Redist-LinuxX64.tar.gz](https://public.dhe.ibm.com/ibmdl/export/pub/software/websphere/messaging/mqdev/redist/9.1.1.0-IBM-MQC-Redist-LinuxX64.tar.gz)

We are in the process of fixing the build in the master branch to automatically download the redistributable client file.

**Comment by 344271** [comment]
Hello,
I have installed IBM-MQC-Redist-Win64 on my Windows Pc, but I am still getting the error :
fatal error: cmqc.h: No such file or directory
   54 | #include <cmqc.h>
      |          ^~~~~~~~
compilation terminated.
Could you please help. Many Thanks in advance.

**Comment by arthurbarr** [comment]
@344271 what are you trying to build?  I'd suggest perhaps raising a new issue, as this issue is nearly two years old, and might not be quite the same.  I don't think there's any reason to install the MQ client on your Windows machine, in order to build a queue manager container.
