### ISSUE TITLE
/opt/mqm/samp/bin/amqsputc: error while loading shared libraries: libmqic_r.so: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by patrick-marie** [ibm-messaging/mq-container#281]
I created a mqadvanced-server image with Ubuntu and MQ 9.0.5.0. The resulting container works find, but I cannot use "amqsputc" with it because the library "libmqic_r.so" is missing (it is not just a problem of LD_LIBRARY_PATH, it is really missing in the MQ directories). My best guess is that this issue occurs because the MQSeriesClient package was not selected when building the image. Could you please confirm?

**Comment by parrobe** [comment]
Hi @patrick-marie - MQ 9.0.5.0 is no longer in support due to the Continous delivery support model that was in effect when 9.0.5 was released that stated we will support the latest 2 release. For reference the latest two releases are 9.1.0 and 9.1.1). The new support model that came into effect in 9.1 now says that we will support a CD release for a year or if 2 other releases are made (whichever is longer).

**That said.** Yes you are correct, if you've built an image of MQ which does not install the Client packages then you will not have the client libraries needed by MQ client applications to run. You can fix this by supplying the make argument `MQ_PACKAGES ` with the packages you want to install. The defaults are: 

- "MQSeriesRuntime-*.rpm MQSeriesServer-*.rpm MQSeriesJava*.rpm MQSeriesJRE*.rpm MQSeriesGSKit*.rpm MQSeriesMsg*.rpm MQSeriesSamples*.rpm MQSeriesAMS-*.rpm MQSeriesWeb-*.rpm" for ubuntu
- "MQSeriesRuntime-*.rpm MQSeriesServer-*.rpm MQSeriesJava*.rpm MQSeriesJRE*.rpm MQSeriesGSKit*.rpm MQSeriesMsg*.rpm MQSeriesSamples*.rpm MQSeriesAMS-*.rpm MQSeriesWeb-*.rpm" for RHEL/Linux

**Comment by patrick-marie** [comment]
Thanks for your answer.

**Comment by gordo1337** [comment]
Hi! 
Found this issue here on Github, and thought it would be good to inform here. 

I recently did and upgrade of fixpack IBM MQ 9.3 LTS 9.3.0.5 (from 9.3.0.4) 
And got the same error as above,  ( libmqic_r.so: cannot open shared object file: ((When trying to do strmqm)))

And would like to just shed light to the problem. 
I am using IBM MQ 9.3 for Linux x 64.

And i have been opening a case to IBM also. (TS013070824)


Seems to be some ppl in the past who have gotten this same error but only a few. Never solved the issue. 

Greetings Gordo 1337
