### ISSUE TITLE
MQ Web console on RHEL image does not start when the container is started

### ISSUE THREAD

**Issue by APC02** [ibm-messaging/mq-container#288]
Hi,

I have created an RHEL base image to include web console, by adding package MQWebSeries*.rpm in Makefile-RHEL. Once I start the container, I have to start the web console by running _strmqweb_ manually from inside the container. 
Shouldn't the web console start automatically when the container starts ?

**Comment by arthurbarr** [comment]
Currently, the RHEL image is a standard out-of-the-box MQ installation, with only the Queue Manager started by default.  We don't start the web server automatically, except in our opinionated developer-specific extensions (in our developer image, we make a few extra choices on behalf of the user, like wanting the web server to be started).  If you want to start the web server automatically, then look at [webserver.go](https://github.com/ibm-messaging/mq-container/blob/master/cmd/runmqserver/webserver.go).  If the code is built with the `mqdev` tag, then the [dev post init step](https://github.com/ibm-messaging/mq-container/blob/4d4051312eb9d95a086e2ead76482d1f1616d149/cmd/runmqserver/post_init_dev.go) calls that code and the web server will start.  Otherwise the [default post init step](
https://github.com/ibm-messaging/mq-container/blob/4d4051312eb9d95a086e2ead76482d1f1616d149/cmd/runmqserver/post_init_other.go) is used.
