### ISSUE TITLE
ibmcom/mq:9.1.2.0 Queue manager widget does not have create new Queue Manager button

### ISSUE THREAD

**Issue by GeoffSeloana** [ibm-messaging/mq-container#351]
`ibmcom/mq:9.1.2.0` Queue manager widget does not have `create new` Queue Manager button

**Comment by arthurbarr** [comment]
This is intentional, as it's considered bad practice to have more than one Queue Manager in a single container.  If you want to turn the widget back to the non-containerised settings, you need to change the Liberty [`mqwebuser.xml.tpl`](https://github.com/ibm-messaging/mq-container/blob/b8a7167c4ea07aceac7639c7bb2d944430b13dfa/web/installations/Installation1/servers/mqweb/mqwebuser.xml.tpl) to remove the setting of `managementMode` to `externallyprovisioned`
