### ISSUE TITLE
Error Connecting two Queue Manager Containers in Sender-Receiver Channels

### ISSUE THREAD

**Issue by amak313** [ibm-messaging/mq-container#374]
When I run two Containers with published ports and create a sender channel on one then a receiver channel with the same name on the other, I add the connection name as the either the host IP with published port it doesn't start, I add the connection name as the IP of the second Queue Manager under the default docker bridge with 1414 as the port, it doesn't work as well.

also I can't find either yum package or any network related packages to enable me to ping, telnet, or even ifconfig on the server

I have Docker for windows version 2.1.0.4 having Engine version 19.03.4
Microsoft Windows 10 Pro version 10.0.17763 Build 17763 X64-based
the commands I used to create the two queue managers' containers are as follows:

docker run --name qm1server  --env LICENSE=accept   --env MQ_QMGR_NAME=QM1  --detach --publish 10414:1414 --publish 10443:9443 --publish 10157:9157 --volume qm1data:/mnt/mqm  ibmcom/mq
docker run --name qm2server  --env LICENSE=accept   --env MQ_QMGR_NAME=QM2  --detach --publish 11414:1414 --publish 11443:9443 --publish 11157:9157 --volume qm2data:/mnt/mqm  ibmcom/mq

kindly let me know if this is a common problem or not, & if anyone has the resolution to this.

**Comment by arthurbarr** [comment]
I think the problem here is security.  The "ibmcom/mq" image is an MQ Advanced for Developers image, to which we have added a [default developer configuration](https://github.com/ibm-messaging/mq-container/blob/master/docs/developer-config.md).  This configuration sets up security with two channels (one for admin, one for application messaging), and adds a back-stop rule to prevent any other channel auth.  So to get this going, you need to add something like this on the queue manager with the receiver channel:

```
SET CHLAUTH(QM2.QM1) TYPE(ADDRESSMAP) ADDRESS('*') USERSRC(CHANNEL)
```

The following is a more complete example.  On QM1:

```
DEFINE CHANNEL(QM2.QM1) CHLTYPE(RCVR)
SET CHLAUTH(QM2.QM1) TYPE(ADDRESSMAP) ADDRESS('*') USERSRC(CHANNEL) 
DEFINE QLOCAL(MYQUEUE)
START CHANNEL(QM2.QM1)
```

On QM2:
```
DEFINE QLOCAL(TO.QM1) USAGE(XMITQ)
DEFINE CHANNEL(QM2.QM1) CHLTYPE(SDR) CONNAME('qm1server(1414)') XMITQ(TO.QM1)
DEFINE QREMOTE(MYQUEUE_REMOTE) RNAME(MYQUEUE) RQMNAME(QM1) XMITQ(TO.QM1)
START CHANNEL(QM2.QM1)
```

If you add the Docker option `--link qm1server` when you run QM2, Docker will create an entry in the `/etc/hosts` file for the container, to allow you to use the name `qm1server` as I've used in my example.  You could equally use the host IP address with the port forwarding, as in your example.
