### ISSUE TITLE
Support for no-new-privs in docker env

### ISSUE THREAD

**Issue by bony-cas** [ibm-messaging/mq-container#377]
Our docker environment is managed by another team. They recently added the no-new-privs security flag on one cluster (and plan to roll this out to all clusters). On the cluster with no-new-privs set we get the below error..
Error 119 starting queue manager: AMQ7077E: You are not authorized to perform the requested operation.

We are still analysing the problem, but the current indications are that this error is directly related to the new security flag. Does the MQ image support no-new-privs security flag? 

Our current build is 9.1.0.0 - we are planning to build 9.1.3 in the next few weeks.

**Comment by arthurbarr** [comment]
The `no-new-privs` flag affects the use of binaries with the `setuid` bit set.  MQ uses the `setuid` bit to ensure that programs are run as user "mqm".  My understanding is that if this bit is set, then containers which disallow new privs will fail.  This is a core limitation of MQ in currently released versions.

**Comment by bony-cas** [comment]
Thanks Arthur. Are there any plans to engineer the MQ image to support no-new-privs?

**Comment by cantorek** [comment]
@arthurbarr 
Can operations that require root ie.
https://github.com/ibm-messaging/mq-container/blob/master/cmd/runmqdevserver/main.go#L36
be moved to the image creation phase?
This way we could try to run container as mqm user (or su) which should solve this issue.

Thanks,
Oskar

**Comment by arthurbarr** [comment]
@cantorek That particular example is not possible to put in the image creation phase.  In general, it is not advisable to bake user passwords into a built-time artifact, so we allow you set the password with an environment variable.  That code only gets invoked if you set that environment variable, so you can easily avoid it, and bake a password into the image, if that's what you want.  Note that this feature is only for MQ Advanced for Developers — for production use, [we'd recommend](https://www.ibm.com/support/knowledgecenter/en/SSFKSJ_9.1.0/com.ibm.mq.mcpak.doc/auth_for_mcpak.htm) that you use an LDAP server instead of local OS users.

Note that this is really independent of the original question on this issue, which is about `no-new-privs`.

**Comment by arthurbarr** [comment]
@bony-cas This isn't a limitation of the MQ image, but rather a fact of how the MQ works.  We are looking into improving this, but I can't share any specific plans at the moment.

**Comment by cantorek** [comment]
@arthurbarr Fair point on password and thanks for the hint with env variable.

> Note that this is really independent of the original question on this issue, which is about `no-new-privs`.

No, it really is. As you need root to run runmqdevserver, later on suid binaries are run and privs are changed - this doesn't work.
However, you can run runmqserver -dev (same as here https://github.com/ibm-messaging/mq-container/blob/1aab07c6ed190929a46fa9f1a277f71752225996/cmd/runmqdevserver/main.go#L175) as mqm user and no change in privileges occurs, this works just fine (I think, not an mqm expert ;-).

**Comment by arthurbarr** [comment]
You can now use the "no-install" packages for MQ in containers.  When using these packages, you just extract the MQ files, and RPM is not used.  There is no longer any use of `mqm`, and no files have `setuid` bits set.  This does have the effect that the OS users can no longer be used, as MQ used elevated permissions to check passwords.
