### ISSUE TITLE
User 'app' requires password to connect to DEV.APP.SVRCONN with default settings

### ISSUE THREAD

**Issue by fxlae** [ibm-messaging/mq-container#387]
From my understanding, the documentation of the [default developer config](https://github.com/ibm-messaging/mq-container/blob/master/docs/developer-config.md) implies that you don't need a password for connecting to the DEV.APP.SVRCONN channel with the 'app' user. Relevant parts:

- _"User app for messaging (in a group called mqclient). No password by default."_
- _"Users in mqclient group have been given access connect to all queues and topics starting with DEV.** and have put, get, pub, sub, browse and inq permissions."_
- _"DEV.APP.SVRCONN - does not allow administrative users to connect. Password is optional unless you choose a password for app users."_

However, I'm getting the following errors...

Exception in Java client (based on this [tutorial](https://developer.ibm.com/messaging/learn-mq/mq-tutorials/develop-mq-jms/))
`MQ call failed with compcode '2' ('MQCC_FAILED') reason '2035' ('MQRC_NOT_AUTHORIZED').`

Container log:
```
AMQ5534E: User ID 'app' authentication failed
AMQ5542I: The failed authentication check was caused by the queue manager CONNAUTH CHCKCLNT(REQDADM) configuration.
```

The container is started with
`docker run --env LICENSE=accept --env MQ_QMGR_NAME=QM1  --publish 1414:1414 --publish 9443:9443 --detach --rm ibmcom/mq`

As soon as I define a password (`--env MQ_APP_PASSWORD=...`), the connection is successful.

Is this behavior intended? If yes, how can I disable it?

**Comment by parrobe** [comment]
Looking at the tutorial i suspect the issue is that even though the container is started in a way to not require a password to connect to the `DEV.APP.SVRCONN` channel your application is still sending a password for the app user. When MQ gets a connection with a userid and password supplied it will *always* check them to make sure they are valid and because you haven't set `--env MQ_APP_PASSWORD=....` the passwords are unlikely to match. (Also why it works when you do set it)

Try commenting out the following lines in your program, recompiling and trying again:

```java
cf.setBooleanProperty(WMQConstants.USER_AUTHENTICATION_MQCSP, true);
cf.setStringProperty(WMQConstants.USERID, APP_USER);
cf.setStringProperty(WMQConstants.PASSWORD, APP_PASSWORD);
```

**Comment by fxlae** [comment]
Of course. Thank you.
