### ISSUE TITLE
Backward compability for older MQ versions

### ISSUE THREAD

**Issue by arthurbarr** [ibm-messaging/mq-container#39]
The current code uses the `crtmqdir` utility to create the MQ directory structure.  This utility was introduced in MQ V9.0.3.  MQ is supported in Docker containers back to MQ V8.0.0.4.  In these older versions, you need to use the (undocumented) `amqicdir` utility.

The code should be updated to invoke `amqicdir -i -f` if `/opt/mqm/bin/crtmqdir` does not exist.

We should also ensure that the code gracefully handles using an older version for the JSON logging (which wasn't introduced until MQ V9.0.4), and is assumed when mirroring error logs.

**Comment by parrobe** [comment]
Although crtmqdir is one of the issues around this code being backwards compatible. The other issue is that 8 and 9 LTS versions of MQ do not supply a Debian install image. This means in order to be backwards compatible we'd also have to modify the `install-mq.sh` and `Makefile` script to recognize this and install using the RPM instead.

**Comment by arthurbarr** [comment]
We have decided not to address this issue.  Instead, users can use the [mq-docker](https://github.com/ibm-messaging/mq-docker) sample to create container images for older versions of MQ.
