### ISSUE TITLE
Configuring AMQP in ibmcom/mq

### ISSUE THREAD

**Issue by fbsantana2020** [ibm-messaging/mq-container#413]
Is it possible to configure amqp in mq (https://hub.docker.com/r/ibmcom/mq/) ? How Can I add lib amqp in the docker ?

tks

**Comment by arthurbarr** [comment]
It isn't enabled in the pre-built image available on Docker Hub.  You would have to build your own image using the code in this repository, altering the `MQ_PACKAGES` environment variable to install the extra package.

**Comment by drmartinberger** [comment]
Hi @arthurbarr,
would also be interested to use a Docker image where AMPQ Service is activated.

Can you please elaborate in more detail what steps need to be taken in order to extend the existing image? Is it really that simple to extend the appearances of `MQ_PACKAGES` in [all appearances](https://github.com/ibm-messaging/mq-container/search?q=MQ_PACKAGES) with `MQSeriesAMQP*.rpm`?

Thank you!

**Comment by habaza84** [comment]
@drmartinberger 
Wondering if you figured out how to extend the existing image to AMQP packages? can you share? I am interested on the same thing.

**Comment by drmartinberger** [comment]
@habaza84
did not get any feedback to my question above.

**Comment by chughts** [comment]
See Step 1 of this tutorial - https://developer.ibm.com/tutorials/mq-running-ibm-mq-apps-on-quarkus-and-graalvm-using-qpid-amqp-jms-classes/#step-1-set-up-the-amqp-channel-in-ibm-mq
