### ISSUE TITLE
Missing releases: 9.2.4, 9.2.5, 9.2.0.5

### ISSUE THREAD

**Issue by davidkarlsen** [ibm-messaging/mq-container#479]
Several releases are missing for this repo: https://www.ibm.com/support/fixcentral/swg/selectFixes?product=ibm%2FWebSphere%2FWebSphere+MQ&fixids=9.2.0-IBM-MQ-UbuntuLinuxPPC64LE-FP0005&source=myna&myns=swgws&mynp=OCSSFKSJ&mync=E&cm_sp=swgws-_-OCSSFKSJ-_-E&function=fixId&parent=ibm/WebSphere - is it still maintained?

**Comment by arthurbarr** [comment]
This sample works with multiple versions of MQ.  You can use any of the mentioned versions of MQ with the current sample (for example, by changing the `MQ_VERSION` environment variable as described [here](https://github.com/ibm-messaging/mq-container/blob/master/docs/building.md)).  Sometimes we update the sample to take advantage of new features (like Native HA, when that was released in 2021), but otherwise it should be backward compatible.

**Comment by davidkarlsen** [comment]
@arthurbarr Sure, but I want to use the ready-built images on dockerhub and avoid building them myself.

**Comment by arthurbarr** [comment]
This repo is for the sample code, which is why I closed the issue.  New images will be made on Docker Hub at some point, but there is currently a delay between the MQ release and the Docker Hub release, which we're working on.

**Comment by davidkarlsen** [comment]
@arthurbarr You might want to fix the docs at https://hub.docker.com/r/ibmcom/mq/ in that case, as it points to this repo for registering issues.

**Comment by arthurbarr** [comment]
FYI the MQ 9.2.5 image is now available from the IBM Container Registry: icr.io/ibm-messaging/mq:9.2.5.0-r1
