### ISSUE TITLE
Do the branches map to the IBM products versions? 

### ISSUE THREAD

**Issue by ChrWeissDe** [ibm-messaging/mq-container#514]
I need some guideline to select the correct branch for our MQ custom builds. 

Our goal is to build a "MQ LTS Container Image". From a MQ product perspective this is 9.3.0.x (last one: 9.3.0.2; IBM product part for the linux base image:  M090XML)

So taking a look at the repo here I understand to go for the 9.3.0 branch. 
However I also noticed that the branch 9.3.1 differs quite from 9.3.0 - and has some other/ new content. 

Thus what is the indent / strategy / recommendation here? 
Looking forward to a short feeedback - Thanks in adance

**Comment by arthurbarr** [comment]
The 9.3.1 branch differs because it's being actively developed.  I can't recall any specific changes in 9.3.1 which mean you couldn't use the latest code with 9.3.0 if you wanted to.  If you want to be safe though, then go for the 9.3.0 branch.  Remember that this is just a sample, so it's largely up to you what you build!
