### ISSUE TITLE
Build devserver error: missing tar files

### ISSUE THREAD

**Issue by nordnet-robkui** [ibm-messaging/mq-container#533]
When I clone this repository and run `make build-devserver`on my Mac M1, I get the following error:
```bash
curl --fail --location https://public.dhe.ibm.com/ibmdl/export/pub/software/websphere/messaging/mqadv/9.3.3.1-IBM-MQ-Advanced-for-Developers-Non-Install-LinuxARM64.tar.gz --output downloads/9.3.3.1-IBM-MQ-Advanced-for-Developers-Non-Install-LinuxARM64.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0   607    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 500
```

There is no tar files under https://public.dhe.ibm.com/ibmdl/export/pub/software/websphere/messaging/mqadv/ at all. The only file that is close to this name is [9.3.3.0-IBM-MQ-Advanced-for-Developers-Win64.zip](https://public.dhe.ibm.com/ibmdl/export/pub/software/websphere/messaging/mqadv/9.3.3.0-IBM-MQ-Advanced-for-Developers-Win64.zip).

This doc also refers to broken files in the `Build your own` section: https://www.ibm.com/support/pages/downloading-ibm-mq-930#containers

**Comment by arthurbarr** [comment]
The MQ Advanced for Developers build wasn't updated for the 9.3.3.1 fix release.  However, for now, you can set the MQ version to use as an environment variable, e.g. `MQ_VERSION=9.3.3.0 make build-devserver`

**Comment by arthurbarr** [comment]
OK. I've just looked again, and I realise I was mistaken earlier.  The files are there, including the following:

- [9.3.3.0-IBM-MQ-Advanced-for-Developers-Non-Install-LinuxARM64.tar.gz](https://public.dhe.ibm.com/ibmdl/export/pub/software/websphere/messaging/mqadv/9.3.3.0-IBM-MQ-Advanced-for-Developers-Non-Install-LinuxARM64.tar.gz)   2023-06-29 09:00  486M  
- [9.3.3.0-IBM-MQ-Advanced-for-Developers-Non-Install-LinuxPPC64LE.tar.gz](https://public.dhe.ibm.com/ibmdl/export/pub/software/websphere/messaging/mqadv/9.3.3.0-IBM-MQ-Advanced-for-Developers-Non-Install-LinuxPPC64LE.tar.gz) 2023-06-20 05:01  516M  
- [9.3.3.0-IBM-MQ-Advanced-for-Developers-Non-Install-LinuxS390X.tar.gz](https://public.dhe.ibm.com/ibmdl/export/pub/software/websphere/messaging/mqadv/9.3.3.0-IBM-MQ-Advanced-for-Developers-Non-Install-LinuxS390X.tar.gz)   2023-06-20 05:00  564M  
- [9.3.3.0-IBM-MQ-Advanced-for-Developers-Non-Install-LinuxX64.tar.gz](https://public.dhe.ibm.com/ibmdl/export/pub/software/websphere/messaging/mqadv/9.3.3.0-IBM-MQ-Advanced-for-Developers-Non-Install-LinuxX64.tar.gz)     2023-06-20 06:01  562M  
- [9.3.3.1-IBM-MQ-Advanced-for-Developers-Non-Install-LinuxARM64.tar.gz](https://public.dhe.ibm.com/ibmdl/export/pub/software/websphere/messaging/mqadv/9.3.3.1-IBM-MQ-Advanced-for-Developers-Non-Install-LinuxARM64.tar.gz)   2023-09-08 10:01  463M  
- [9.3.3.1-IBM-MQ-Advanced-for-Developers-Non-Install-LinuxPPC64LE.tar.gz](https://public.dhe.ibm.com/ibmdl/export/pub/software/websphere/messaging/mqadv/9.3.3.1-IBM-MQ-Advanced-for-Developers-Non-Install-LinuxPPC64LE.tar.gz) 2023-09-08 10:01  493M  
- [9.3.3.1-IBM-MQ-Advanced-for-Developers-Non-Install-LinuxS390X.tar.gz](https://public.dhe.ibm.com/ibmdl/export/pub/software/websphere/messaging/mqadv/9.3.3.1-IBM-MQ-Advanced-for-Developers-Non-Install-LinuxS390X.tar.gz)   2023-09-08 11:01  541M  
- [9.3.3.1-IBM-MQ-Advanced-for-Developers-Non-Install-LinuxX64.tar.gz](https://public.dhe.ibm.com/ibmdl/export/pub/software/websphere/messaging/mqadv/9.3.3.1-IBM-MQ-Advanced-for-Developers-Non-Install-LinuxX64.tar.gz)

I listed these using the first link you provided.  So it's possible that there's an intermittent problem with the server.  If you can download the file independently of the Makefile, just put in the `downloads` directory, and the Makefile should spot it's already there, and won't try and download again (e.g. if the problem is somehow the connectivity from your shell environment, or is just intermittent).

**Comment by nordnet-robkui** [comment]
Probably some intermittent problem as you said, because now all files are listed fine using the link. Thank you.
