### ISSUE TITLE
Logs in mqhtpass.log are growing uncontrollably and consume all Pod PVC storage

### ISSUE THREAD

**Issue by xeberth** [ibm-messaging/mq-container#543]
### Logs in mqhtpass.log are growing uncontrollably and consume all Pod PVC storage

We deployed MQ container on Kuberentees using the [AWSEKS](https://github.com/ibm-messaging/mq-helm/blob/9.3.0/samples/AWSEKS/deploy/secureapp_nativeha.yaml) example as baseline.

After perform some testing we found that `mqhtpass.log` file generated under `/var/mqm/errors` in pod filesystem is growing uncontrollably. 

When we investigate we found that the log file is full of this authentication error message:

`{"loglevel":"DEBUG", "ibm_datetime":"2023-10-26T21:44:15.452Z", "ibm_processId":"6697", "host":"xxxxxxxx-ibm-mq-0", "module":"src/mqhtpass.c:284", "message":"mqhtpass: User authentication failed user=eouserx effuser=eouserx    applname=WebSphere MQ Client for Javaeouserx      eouserx    cspuser=eouserx   cc=1 reason=0"}`

We already added "eouserx" as "PRINCIPAL" by using the `SET AUTHREC` command, however seems that is not the right way, since based on error logs seems the user "eouserx" does not have permission to authenticate into qmgr.

By reading documentation, we discovered that IBM container implement by default the [MQ Connection Authentication (CONNAUTH)](https://github.com/ibm-messaging/mq-container/blob/master/docs/pluggable-connauth.md#queue-manager-connection-authentication-using-a-htpasswd-file) . So basically every user who tries to authenticate to **QM** and who is not registered in the `/etc/mqm/mq.htpasswd` file will cause an error message in `/var/mqm/errors/mqhtpass.log`, even if it was added manually with `SET AUTHREC` command. It's right?

The problem here is that this **CONNAUTH** errors  generates a tons of `DEBUG `logs that quickly fill the **QM PVC** and causing pods entering in **Crash loopback**. 
When we inspect the pods logs we found errors like this: `write /var/mqm/web/installations/Installation1/servers/mqweb/configDropins/defaults/jvm.options: no space left on device`.
However if we cleanup this log file from volume the pods run normally again.

Documentation in [MQ Connection Authentication (CONNAUTH)](https://github.com/ibm-messaging/mq-container/blob/master/docs/pluggable-connauth.md#queue-manager-connection-authentication-using-a-htpasswd-file) says: `This new feature is enabled only when environment variable --env MQ_CONNAUTH_USE_HTP=true is set while creating a container.` 

We verified and found this environment variable is used by default as per you can see [here](https://github.com/ibm-messaging/mq-container/blob/9.3.0/Dockerfile-server#L174)

Then we tried to deactivate this by build a new Docker Image and adding an extra layers with:

```
ENV MQ_CONNAUTH_USE_HTP=false
ENV DEBUG=false
```
Our base container image version is: `9.3.0.5-r1`

However we found that error logs still coming into `/var/mqm/errors/mqhtpass.log` and consuming pod PVC space, however if we go into QM active pod we can see that environment variables are present:
```
bash-4.4$ env | grep MQ_CONNAUTH_USE_HTP
MQ_CONNAUTH_USE_HTP=false
bash-4.4$ env | grep -i debug
DEBUG=false
```

### Based on that we have the following questions:

1.- What is the way to add a custom user in `/etc/mqm/mq.htpasswd` to avoid this error logs without having to rebuild the docker image every time a user needs to be added into QMGR?

2.- What is the way to disable the CONNAUTH feature or DEBUG level logging, since it is not recommended in a production environment, and what effects would it have regarding the MQ ADMIN and MQ APP users that comes by default in the image?. 

3.- If it is not possible to disable this feature or add users on demand, how can we configure a log rotation in `/var/mqm/errors/mqhtpass.log` so that this log file does not exceed a certain number of entries?

We will appreciate your guidance on this.

**Comment by arthurbarr** [comment]
The MQ Advanced for Developers sample provides two users: `admin` and `app` via a custom HTPasswd auth service.  These users are provided in the unsupported MQ Advanced for Developers image and sample, to help users get going.  It is not considered suitable for production use (in part due to the lack of log rotation), and was never intended for anything other than individual developer use cases.

The sample code is however provided, and if you wish to use it in production, then it should be considered as just a sample, and therefore your own code to maintain.

The "debug" messages should only be written if the `DEBUG` environment variable is set to to `true` or `1`, so that's probably the simplest solution for you in the short term.  You can also disable the HTPasswd service by setting `MQ_CONNAUTH_USE_HTP` environment variable to `false`.  Also see [User authentication and authorization for IBM MQ in containers](https://www.ibm.com/docs/en/ibm-mq/9.3?topic=containers-user-authentication-authorization-mq-in)
