### ISSUE TITLE
building image 9.4.0.0 failes

### ISSUE THREAD

**Issue by alemert** [ibm-messaging/mq-container#569]
Building MQ Image 9.3.5.1 works fine, so I assume the basic setup in my building environment is ok.
Building MQ Image 9.4.0.0 failes, as well for development edition as for production version.

Building Development Edition:
` make > /tmp/mq-9400-dev.stdout 2>/tmp/mq-9400-dev.stderr
`
Building Prodcution Version:
` make MQ_ARCHIVE=9.4.0.0-IBM-MQ-Advanced-Non-Install-LinuxX64.tar.gz build-advancedserver > /tmp/mq-9400-prd-stdout.log 2>/tmp/mq-9400-prd-stderr.log
` 

[mq-9400-dev-stderr.log](https://github.com/user-attachments/files/16232253/mq-9400-dev-stderr.log)
[mq-9400-dev-stdout.log](https://github.com/user-attachments/files/16232254/mq-9400-dev-stdout.log)
[mq-9400-prd-stderr.log](https://github.com/user-attachments/files/16232334/mq-9400-prd-stderr.log)
[mq-9400-prd-stdout.log](https://github.com/user-attachments/files/16232335/mq-9400-prd-stdout.log)

**Comment by RapTho** [comment]
+1

**Comment by arthurbarr** [comment]
I suspect that the problem is that MQ 9.4.0.0 is using the Red Hat Universal Base Image version 9.  The logs indicate that you are using [Podman 1.6.4](https://github.com/containers/podman/releases/tag/v1.6.4), which is very old (4.5 years).  Based on the kernel version, it looks like you're using RHEL 8.2, which is [out of Red Hat EUS support](https://access.redhat.com/support/policy/updates/errata/).  Although technically [Red Hat say that UBI 9 is supported on a RHEL 8 host](https://access.redhat.com/support/policy/rhel-container-compatibility), they probably mean a patched version of RHEL 8.  Red Hat also say on that page:

> There are known limitations when running a newer container image on an older container host and while this configuration often works, such a configuration can introduce additional risk and compatibility problems. If customers run into these limitations, Red Hat recommends upgrading the container host.

**Comment by RapTho** [comment]
Facing the same issue for MQ 9.4.0.0 with podman version 4.9.4-rhel on RHEL 8.9

**Comment by arthurbarr** [comment]
I've just built the dev container successfully on a clean RHEL 8.10 box with Podman 4.9.4, so unless it's specific to RHEL 8.10 (not impossible), it might be something else.  Is it possible to give any more details about your environment?  Having the stdout and stderr in separate files makes it very difficult to follow.

**Comment by alemert** [comment]
I have RHEL 8.2 and podman 1.6.4. 
I wasn't aware I'm that behind on podman. 
I'll migrate the build environment to RHEL 8.9 / podman 4.6.1.  and will get back with new logs.

**Comment by arthurbarr** [comment]
Based on an offline discussion with @RapTho , his problem was having the tar.gz containing RPMs, and not the "no-install" version.  So this might be a separate problem, and it does seem worth upgrading the RHEL and Podman versions.

**Comment by alemert** [comment]
I can build development image with: RHEL 8.10 and podman 4.9.4
I'm confident, that it will work with production version as well.
Thanks for your support.
