### ISSUE TITLE
Issue with docker-compose 

### ISSUE THREAD

**Issue by yann-re** [ibm-messaging/mq-container#74]
Hello,

When I launch mqserver with docker run it work well, however when I try to launch it with docker-compose I have an error message about /mnt/mqm and xfs : 
```
$ cat docker-compose.yml
version: '3'
services:
    mqseries:
        image: ibmcom/mq:9-cd
        ports:
            - "1414:1414"
        container_name: mqserver
        environment:
            - LICENSE=accept
            - MQ_QMGR_NAME=MQAZ01
        volumes:
            - mqseries-volume:/var/mqm
        stdin_open: true
        tty: true
        restart: always
volumes:
    mqseries-volume:
```

```
$ docker-compose up
Creating volume "mqserver_mqseries-volume" with default driver
Creating mqserver ... done
Attaching to mqserver
mqserver    | 2018-05-02T13:14:49.525Z Set password for "admin" user
mqserver    | 2018-05-02T13:14:49.566Z Using queue manager name: MQAZ01
mqserver    | 2018-05-02T13:14:49.567Z CPU architecture: amd64
mqserver    | 2018-05-02T13:14:49.567Z Linux kernel version: 3.10.0-862.el7.x86_64
mqserver    | 2018-05-02T13:14:49.567Z Base image detected: Ubuntu 16.04.4 LTS
mqserver    | 2018-05-02T13:14:49.568Z Maximum file handles: 805428
mqserver    | 2018-05-02T13:14:49.568Z Running as user ID 0 (root) with primary group 0
mqserver    | 2018-05-02T13:14:49.568Z Detected capabilities: AUDIT_WRITE,CHOWN,DAC_OVERRIDE,FOWNER,FSETID,KILL,MKNOD,NET_BIND_SERVICE,NET_RAW,SETFCAP,SETGID,SETPCAP,SETUID,SYS_CHROOT
mqserver    | 2018-05-02T13:14:49.568Z Detected 'xfs' volume mounted to /mnt/mqm/data
mqserver    | 2018-05-02T13:14:49.568Z Detected /mnt/mqm has filesystem type ''
mqserver    | 2018-05-02T13:14:49.569Z Error: Unable to change ownership of /mnt/mqm/data
mqserver    | 2018-05-02T13:14:49.569Z [chown /mnt/mqm/data: permission denied]
```

I can workaround this by creating a specific volume for /mnt/mqm but I think there is a bug here. Can you help with this ? 

Regards.

**Comment by arthurbarr** [comment]
I'm a bit confused, as it doesn't look like your error log matches the `docker-compose.yaml` file.

You need to make sure you mount volumes to `/mnt/mqm` and not directly to `/var/mqm`.  This is needed to handle file permissions in some orchestrated environments.

**Comment by cra1gl1** [comment]
Arthur,
Do you mean we should pass --volume /var/example:/mnt/mqm instead of --volume /var/example:/var/mqm in docker run command ?

**Comment by parrobe** [comment]
@cra1gl1 - Yes that is correct. The control program `runmqserver` which is the container entry point expects persistent volumes to be mounted to `/mnt/mqm` not `/var/mqm` as they used to be in the mq-docker repository. If you do mount the volume to `/var/mqm` we see errors around it being an unsupported filesystem.

The main reason for this change is so that this image can be used with IBM Cloud persistent volumes.

**Comment by cra1gl1** [comment]
Thank you Rob. I've another question on datapath /mnt/mqm/data. Looks like the createvol is supposed to create /mnt/mqm/data with 0755 permissions? But, I see 775 on it. Am I missing something? 
(mq:9.0.5.0)root@:/# ls -lrt /mnt/mqm/
total 4
drwxrwsr-x 14 mqm mqm 4096 May 18 18:50 data
(mq:9.0.5.0)root@:/#

**Comment by parrobe** [comment]
`createvol` will create the volume with 0755 but a later part of the runmqserver program will call the MQ program `crtmqdir` which performs a variety of operations on `/var/mqm` including ensuring the permissions and ownership of it matches what IBM MQ needs. I imagine at this point we change the ownership to `mqm:mqm` and the permissions to 0775. 

MQ will require the user&group mqm to have read,write and execute permissions on `/var/mqm` in order to be able to operate correctly. We could make `createvol` set the correct permissions (0775 mqm:mqm) but given `crtmqdir` will handle all that for us we use `createvol` to ensure that the volume is accessible and can be altered by MQ.

**Comment by parrobe** [comment]
Hi @yann-re - we haven't from you in 2 weeks, as such i'm going to close this issue. Please take a look at the comments above and see if changing your docker-compose.yml to use `/mnt/mqm` as the volume mount instead of `/var/mqm` works:

```version: '3'
services:
    mqseries:
        image: ibmcom/mq:9-cd
        ports:
            - "1414:1414"
        container_name: mqserver
        environment:
            - LICENSE=accept
            - MQ_QMGR_NAME=MQAZ01
        volumes:
            - mqseries-volume:/mnt/mqm
        stdin_open: true
        tty: true
        restart: always
volumes:
    mqseries-volume:```
